---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.4.56
  install_strategy: always
  attributes:
    se-users:
      remove_bootstrap: false

verifier:
  name: inspec

platforms:
  - name: centos-7.5
    driver:
      network:
      - ["forwarded_port", {guest: 80, host: 8080, host_ip: "localhost"}]
      - ["forwarded_port", {guest: 443, host: 8043, host_ip: "localhost"}]
  - name: ubuntu-18.04
    driver:
      network:
      - ["forwarded_port", {guest: 80, host: 8180, host_ip: "localhost"}]
      - ["forwarded_port", {guest: 443, host: 8143, host_ip: "localhost"}]

suites:
  - name: default
    run_list:
      - recipe[se_django_app::default]
    data_bags_path: "test/smoke/data_bags"
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      - centos-7.5
      - ubuntu-18.04
