---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 80}]
    - ["forwarded_port", {guest: 443, host: 443}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.2.0
  install_strategy: always
  attributes:
    se-users:
      remove_bootstrap: false

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[app_account_portal::default]
    data_bags_path: "test/smoke/data_bags"
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      - ubuntu-18.04
