---
driver:
  name: ec2
  region: us-west-1
  instance_type: t2.micro
  tags:
    Name: Django Platform
    Service: Infrastructure
    Environment: Test
    Fund: 103010
    Org: 60412
    Department: Systems Engineering

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.10.9
  install_strategy: once
  attributes:
    se_baseline:
      chef_client_version: '14.8.12'
      configure_monitoring: false
    nix_baseline:
      chef_client_version: '14.8.12'
      configure_update: false
      hostname: 'funny.business'
    http_platform:
      admin_email: 'fake-it@make-it'
      apache:
        install_test_suite: true
      cert:
        organization: 'fake_org'
        org_unit: 'fake_unit'
      www:
        additional_aliases:
          funny.business:
            log_level: 'info'
        remove_default_index: false
        create_default_index: true
    django_platform:
      configure_postgres: true
      django_is_system_user: false

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9
  - name: debian-8
  - name: centos-7
  - name: centos-6
  - name: oracle-7.6
  - name: oracle-6.10
  - name: fedora-29
  - name: fedora-28
  - name: amazon2
  - name: amazon-
  - name: sles-15
  - name: windows-2019
    driver:
      image_id: ami-087efd22b572d6bc1
    transport:
      name: winrm
  - name: windows-2016
    transport:
      name: winrm
  - name: windows-2012r2
    transport:
      name: winrm
  - name: windows-2008r2sp1
    transport:
      name: winrm

suites:
  - name: account
    run_list:
      - recipe[se-nix-baseline::default]
      - recipe[account_site::default]
    data_bags_path: "test/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/account
    attributes:
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - centos-7
  - name: faculty
    run_list:
      - recipe[se-nix-baseline::default]
      - recipe[faculty_site::default]
    data_bags_path: "test/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/faculty
    attributes:
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - centos-7
