---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.6.47
  install_strategy: always
  attributes:
    se_baseline:
      chef_client_version: '14.6.47'
    nix_baseline:
      chef_client_version: '14.6.47'
      hostname: 'funny.business'
    http_platform:
      admin_email: 'fake-it@make-it'
    django_platform:
      app_repo:
        path_to_manage_py: 'app/manage.py'
        path_to_http_root: 'app'
        path_to_pip_requirements: 'requirements.txt'
        git_host: 'github.alaska.edu'
        git_user: 'OIT-CSS'
        git_repo: 'ua_account_site'

verifier:
  name: inspec

# Every bento box supported by Chef 14
platforms:
  - name: ubuntu-18.04
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080, host_ip: "localhost"}]
        - ["forwarded_port", {guest: 443, host: 8043, host_ip: "localhost"}]
  - name: ubuntu-16.04
  - name: ubuntu-16.04-i386
  - name: ubuntu-14.04
  - name: ubuntu-14.04-i386
  - name: ubuntu-12.04
  - name: ubuntu-12.04-i386
  - name: debian-9.5
  - name: debian-9.5-i386
  - name: debian-8.11
  - name: debian-8.10-i386
  - name: debian-7.11
  - name: debian-7.11-i386
  - name: centos-7.5
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8180, host_ip: "localhost"}]
        - ["forwarded_port", {guest: 443, host: 8143, host_ip: "localhost"}]
  - name: centos-6.10
  - name: centos-6.10-i386
  - name: centos-5.11
  - name: centos-5.11-i386
  - name: oracle-7.5
  - name: oracle-6.10
  - name: oracle-6.10-i386
  - name: oracle-5.11
  - name: oracle-5.11-i386
  - name: fedora-28
  - name: fedora-27
  - name: fedora-26
  - name: gbailey/amzn2 # 2018.08
  - name: stakahashi/amazonlinux2 # 2017.12
  - name: realreadme/amazon2016.09
  - name: opensuse-leap-15.0
  - name: opensuse-leap-42.3
  - name: freebsd-11.2
  - name: freebsd-11.2-i386
  - name: freebsd-10.4
  - name: freebsd-10.4-i386
  - name: mwrock/Windows2016
    transport:
      name: winrm
  - name: a-mcf/Win2012R2-WMF5-min
    transport:
      name: winrm
  - name: salesforce/server2008r2
    transport:
      name: winrm

suites:
  - name: debian-based
    run_list:
      - recipe[se-nix-baseline::default]
      - recipe[django_platform::default]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    includes:
      - ubuntu-18.04
  - name: rhel-based
    run_list:
      - recipe[se-nix-baseline::default]
      - recipe[django_platform::default]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    includes:
      - centos-7.5
